export const links = [
  '3D-Card',
  '3D-Menu',
  'Calculator',
  'Cigarette',
  'Circular-Progress',
  'Dark-Mode-Menu',
  'Dashboard',
  'Dashboard-II',
  'Delete-Button',
  'Fingerprint-Scanner',
  'Glassmorphism-Card',
  'Indicator',
  'Iphone-Dynamic-Island',
  'Keyboard',
  'Login-Form',
  'Menu-Expand',
  'Menu-Expand-II',
  'Menu-Hover',
  'Prettier-Logo',
  'Responsive-Hover',
  'Rotate-Text',
  'Submit-Button',
  'Switch',
  'Text-Focus-Effect',
  'TikTok-Logo',
  'Typing-Text',
  'Vertical-Menu',
  // 'Learning-Masked-Buttons',
  // 'Learning-Windows-Loading',
];

export const frontendMentor = [
  {
    title: 'Expense chart',
    url: 'https://frontend-mentor-expense-chart-component.vercel.app',
    github: 'https://github.com/RylanZhou/frontend-mentor-expense-chart-component',
  },
  {
    title: 'Intro section',
    url: 'https://frontend-mentor-intro-section-with-dropdown-navigation-kappa.vercel.app/',
    github: 'https://github.com/RylanZhou/frontend-mentor-intro-section-with-dropdown-navigation',
  },
  {
    title: 'Interactive card',
    url: 'https://frontend-mentor-interactive-card-details-form-nine.vercel.app/',
    github: 'https://github.com/RylanZhou/frontend-mentor-interactive-card-details-form',
  },
  {
    title: 'Notifications',
    url: 'https://frontend-mentor-notifications-page-chi.vercel.app/',
    github: 'https://github.com/RylanZhou/frontend-mentor-notifications-page',
  },
  {
    title: 'News Homepage',
    url: 'https://frontend-mentor-news-homepage-gules.vercel.app/',
    github: 'https://github.com/RylanZhou/frontend-mentor-news-homepage',
  },
];
